[package]
name = "evict"
version = "1.0.0"
edition = "2024"

[dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_System_Threading", "Win32_NetworkManagement_IpHelper", "Win32_Networking_WinSock"] }

[dev-dependencies]
proptest = "1.4"
